/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 71
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_meta = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_COMMA = 5,
  anon_sym_EQ = 6,
  anon_sym_enum = 7,
  anon_sym_COLON = 8,
  anon_sym_struct = 9,
  anon_sym_QMARK = 10,
  anon_sym_LBRACK = 11,
  anon_sym_SEMI = 12,
  anon_sym_RBRACK = 13,
  sym_string_type = 14,
  sym_bool_type = 15,
  anon_sym_i8 = 16,
  anon_sym_i16 = 17,
  anon_sym_i32 = 18,
  anon_sym_i64 = 19,
  anon_sym_u8 = 20,
  anon_sym_u16 = 21,
  anon_sym_u32 = 22,
  anon_sym_u64 = 23,
  anon_sym_f32 = 24,
  anon_sym_f64 = 25,
  sym_string_literal = 26,
  sym_integer_literal = 27,
  sym_comment = 28,
  sym_schema = 29,
  sym__declaration = 30,
  sym_meta_decl = 31,
  sym_meta_data_list = 32,
  sym_meta_data_entry = 33,
  sym_enum_decl = 34,
  sym_enum_variant_list = 35,
  sym_enum_variant = 36,
  sym_struct_decl = 37,
  sym_struct_field_list = 38,
  sym_struct_field = 39,
  sym_field_type = 40,
  sym_array_type = 41,
  sym_map_type = 42,
  sym_builtin_type = 43,
  sym_integer_type = 44,
  sym_float_type = 45,
  aux_sym_schema_repeat1 = 46,
  aux_sym_meta_data_list_repeat1 = 47,
  aux_sym_enum_variant_list_repeat1 = 48,
  aux_sym_struct_field_list_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_meta] = "meta",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [anon_sym_enum] = "enum",
  [anon_sym_COLON] = ":",
  [anon_sym_struct] = "struct",
  [anon_sym_QMARK] = "\?",
  [anon_sym_LBRACK] = "[",
  [anon_sym_SEMI] = ";",
  [anon_sym_RBRACK] = "]",
  [sym_string_type] = "string_type",
  [sym_bool_type] = "bool_type",
  [anon_sym_i8] = "i8",
  [anon_sym_i16] = "i16",
  [anon_sym_i32] = "i32",
  [anon_sym_i64] = "i64",
  [anon_sym_u8] = "u8",
  [anon_sym_u16] = "u16",
  [anon_sym_u32] = "u32",
  [anon_sym_u64] = "u64",
  [anon_sym_f32] = "f32",
  [anon_sym_f64] = "f64",
  [sym_string_literal] = "string_literal",
  [sym_integer_literal] = "integer_literal",
  [sym_comment] = "comment",
  [sym_schema] = "schema",
  [sym__declaration] = "_declaration",
  [sym_meta_decl] = "meta_decl",
  [sym_meta_data_list] = "meta_data_list",
  [sym_meta_data_entry] = "meta_data_entry",
  [sym_enum_decl] = "enum_decl",
  [sym_enum_variant_list] = "enum_variant_list",
  [sym_enum_variant] = "enum_variant",
  [sym_struct_decl] = "struct_decl",
  [sym_struct_field_list] = "struct_field_list",
  [sym_struct_field] = "struct_field",
  [sym_field_type] = "field_type",
  [sym_array_type] = "array_type",
  [sym_map_type] = "map_type",
  [sym_builtin_type] = "builtin_type",
  [sym_integer_type] = "integer_type",
  [sym_float_type] = "float_type",
  [aux_sym_schema_repeat1] = "schema_repeat1",
  [aux_sym_meta_data_list_repeat1] = "meta_data_list_repeat1",
  [aux_sym_enum_variant_list_repeat1] = "enum_variant_list_repeat1",
  [aux_sym_struct_field_list_repeat1] = "struct_field_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_meta] = anon_sym_meta,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_string_type] = sym_string_type,
  [sym_bool_type] = sym_bool_type,
  [anon_sym_i8] = anon_sym_i8,
  [anon_sym_i16] = anon_sym_i16,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_i64] = anon_sym_i64,
  [anon_sym_u8] = anon_sym_u8,
  [anon_sym_u16] = anon_sym_u16,
  [anon_sym_u32] = anon_sym_u32,
  [anon_sym_u64] = anon_sym_u64,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_f64] = anon_sym_f64,
  [sym_string_literal] = sym_string_literal,
  [sym_integer_literal] = sym_integer_literal,
  [sym_comment] = sym_comment,
  [sym_schema] = sym_schema,
  [sym__declaration] = sym__declaration,
  [sym_meta_decl] = sym_meta_decl,
  [sym_meta_data_list] = sym_meta_data_list,
  [sym_meta_data_entry] = sym_meta_data_entry,
  [sym_enum_decl] = sym_enum_decl,
  [sym_enum_variant_list] = sym_enum_variant_list,
  [sym_enum_variant] = sym_enum_variant,
  [sym_struct_decl] = sym_struct_decl,
  [sym_struct_field_list] = sym_struct_field_list,
  [sym_struct_field] = sym_struct_field,
  [sym_field_type] = sym_field_type,
  [sym_array_type] = sym_array_type,
  [sym_map_type] = sym_map_type,
  [sym_builtin_type] = sym_builtin_type,
  [sym_integer_type] = sym_integer_type,
  [sym_float_type] = sym_float_type,
  [aux_sym_schema_repeat1] = aux_sym_schema_repeat1,
  [aux_sym_meta_data_list_repeat1] = aux_sym_meta_data_list_repeat1,
  [aux_sym_enum_variant_list_repeat1] = aux_sym_enum_variant_list_repeat1,
  [aux_sym_struct_field_list_repeat1] = aux_sym_struct_field_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_meta] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_string_type] = {
    .visible = true,
    .named = true,
  },
  [sym_bool_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_i8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f64] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_schema] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_meta_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_meta_data_list] = {
    .visible = true,
    .named = true,
  },
  [sym_meta_data_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_variant_list] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field_list] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_field_type] = {
    .visible = true,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_map_type] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin_type] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_type] = {
    .visible = true,
    .named = true,
  },
  [sym_float_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_schema_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_meta_data_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_variant_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_field_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '"', 1,
        ',', 8,
        '-', 3,
        '/', 2,
        ':', 10,
        ';', 13,
        '=', 9,
        '?', 11,
        '[', 12,
        ']', 14,
        '{', 6,
        '}', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(18);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(18);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'b') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'm') ADVANCE(5);
      if (lookahead == 's') ADVANCE(6);
      if (lookahead == 'u') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == '3') ADVANCE(10);
      if (lookahead == '6') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == '1') ADVANCE(12);
      if (lookahead == '3') ADVANCE(13);
      if (lookahead == '6') ADVANCE(14);
      if (lookahead == '8') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == '1') ADVANCE(18);
      if (lookahead == '3') ADVANCE(19);
      if (lookahead == '6') ADVANCE(20);
      if (lookahead == '8') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == '2') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == '4') ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == '6') ADVANCE(26);
      END_STATE();
    case 13:
      if (lookahead == '2') ADVANCE(27);
      END_STATE();
    case 14:
      if (lookahead == '4') ADVANCE(28);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_i8);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 18:
      if (lookahead == '6') ADVANCE(31);
      END_STATE();
    case 19:
      if (lookahead == '2') ADVANCE(32);
      END_STATE();
    case 20:
      if (lookahead == '4') ADVANCE(33);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_u8);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 23:
      if (lookahead == 'm') ADVANCE(35);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_f32);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_f64);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_i16);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_i64);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(37);
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_u16);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_u32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_u64);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_bool_type);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_meta);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 38:
      if (lookahead == 'c') ADVANCE(40);
      END_STATE();
    case 39:
      if (lookahead == 'g') ADVANCE(41);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_string_type);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_meta] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_string_type] = ACTIONS(1),
    [sym_bool_type] = ACTIONS(1),
    [anon_sym_i8] = ACTIONS(1),
    [anon_sym_i16] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [anon_sym_u8] = ACTIONS(1),
    [anon_sym_u16] = ACTIONS(1),
    [anon_sym_u32] = ACTIONS(1),
    [anon_sym_u64] = ACTIONS(1),
    [anon_sym_f32] = ACTIONS(1),
    [anon_sym_f64] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_schema] = STATE(70),
    [sym_meta_decl] = STATE(9),
    [anon_sym_meta] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    STATE(46), 1,
      sym_field_type,
    ACTIONS(13), 2,
      sym_string_type,
      sym_bool_type,
    ACTIONS(17), 2,
      anon_sym_f32,
      anon_sym_f64,
    STATE(11), 2,
      sym_integer_type,
      sym_float_type,
    STATE(13), 3,
      sym_array_type,
      sym_map_type,
      sym_builtin_type,
    ACTIONS(15), 8,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
  [43] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    STATE(48), 1,
      sym_field_type,
    ACTIONS(13), 2,
      sym_string_type,
      sym_bool_type,
    ACTIONS(17), 2,
      anon_sym_f32,
      anon_sym_f64,
    STATE(11), 2,
      sym_integer_type,
      sym_float_type,
    STATE(13), 3,
      sym_array_type,
      sym_map_type,
      sym_builtin_type,
    ACTIONS(15), 8,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
  [86] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    STATE(68), 1,
      sym_field_type,
    ACTIONS(13), 2,
      sym_string_type,
      sym_bool_type,
    ACTIONS(17), 2,
      anon_sym_f32,
      anon_sym_f64,
    STATE(11), 2,
      sym_integer_type,
      sym_float_type,
    STATE(13), 3,
      sym_array_type,
      sym_map_type,
      sym_builtin_type,
    ACTIONS(15), 8,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
  [129] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(61), 1,
      sym_builtin_type,
    ACTIONS(19), 2,
      sym_string_type,
      sym_bool_type,
    ACTIONS(23), 2,
      anon_sym_f32,
      anon_sym_f64,
    STATE(11), 2,
      sym_integer_type,
      sym_float_type,
    ACTIONS(21), 8,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
  [158] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(58), 1,
      sym_integer_type,
    ACTIONS(21), 8,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
  [175] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_enum,
    ACTIONS(29), 1,
      anon_sym_struct,
    STATE(10), 4,
      sym__declaration,
      sym_enum_decl,
      sym_struct_decl,
      aux_sym_schema_repeat1,
  [194] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_QMARK,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [207] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_enum,
    ACTIONS(29), 1,
      anon_sym_struct,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    STATE(7), 4,
      sym__declaration,
      sym_enum_decl,
      sym_struct_decl,
      aux_sym_schema_repeat1,
  [226] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      anon_sym_enum,
    ACTIONS(40), 1,
      anon_sym_struct,
    STATE(10), 4,
      sym__declaration,
      sym_enum_decl,
      sym_struct_decl,
      aux_sym_schema_repeat1,
  [245] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_QMARK,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [257] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_QMARK,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [269] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_QMARK,
    ACTIONS(47), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [282] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 5,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [293] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 5,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [304] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 5,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [315] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [325] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 3,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
  [334] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym_identifier,
    STATE(33), 1,
      sym_meta_data_entry,
    STATE(57), 1,
      sym_meta_data_list,
  [347] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym_identifier,
    STATE(24), 1,
      sym_struct_field,
    STATE(59), 1,
      sym_struct_field_list,
  [360] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      sym_meta_data_entry,
  [373] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    ACTIONS(69), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      aux_sym_meta_data_list_repeat1,
  [386] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    STATE(26), 1,
      aux_sym_enum_variant_list_repeat1,
  [399] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
    ACTIONS(78), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      aux_sym_struct_field_list_repeat1,
  [412] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      sym_enum_variant,
  [425] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    ACTIONS(84), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym_enum_variant_list_repeat1,
  [438] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      sym_identifier,
    STATE(23), 1,
      sym_enum_variant,
    STATE(55), 1,
      sym_enum_variant_list,
  [451] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 3,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
  [460] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(88), 1,
      anon_sym_RBRACE,
    STATE(47), 1,
      sym_struct_field,
  [473] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_RBRACE,
    ACTIONS(90), 1,
      anon_sym_COMMA,
    STATE(35), 1,
      aux_sym_struct_field_list_repeat1,
  [486] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      sym_enum_variant,
  [499] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
    ACTIONS(96), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym_enum_variant_list_repeat1,
  [512] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    ACTIONS(101), 1,
      anon_sym_COMMA,
    STATE(39), 1,
      aux_sym_meta_data_list_repeat1,
  [525] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    STATE(47), 1,
      sym_struct_field,
  [538] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    STATE(35), 1,
      aux_sym_struct_field_list_repeat1,
  [551] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 3,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
  [560] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 3,
      ts_builtin_sym_end,
      anon_sym_enum,
      anon_sym_struct,
  [569] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      sym_meta_data_entry,
  [582] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    ACTIONS(116), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      aux_sym_meta_data_list_repeat1,
  [595] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      sym_identifier,
    STATE(23), 1,
      sym_enum_variant,
    STATE(67), 1,
      sym_enum_variant_list,
  [608] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [616] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym_identifier,
    STATE(44), 1,
      sym_meta_data_entry,
  [626] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [634] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [642] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_LBRACE,
    ACTIONS(122), 1,
      anon_sym_COLON,
  [652] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [660] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [668] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_SEMI,
    ACTIONS(128), 1,
      anon_sym_RBRACK,
  [678] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 2,
      sym_string_literal,
      sym_integer_literal,
  [686] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      sym_identifier,
    STATE(41), 1,
      sym_enum_variant,
  [696] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym_identifier,
    STATE(47), 1,
      sym_struct_field,
  [706] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [714] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      sym_identifier,
  [721] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_COLON,
  [728] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
  [735] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_EQ,
  [742] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
  [749] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_LBRACE,
  [756] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
  [763] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_LBRACE,
  [770] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_COLON,
  [777] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      sym_integer_literal,
  [784] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      sym_identifier,
  [791] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_EQ,
  [798] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_LBRACE,
  [805] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      sym_integer_literal,
  [812] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_RBRACE,
  [819] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_RBRACE,
  [826] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_RBRACK,
  [833] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 129,
  [SMALL_STATE(6)] = 158,
  [SMALL_STATE(7)] = 175,
  [SMALL_STATE(8)] = 194,
  [SMALL_STATE(9)] = 207,
  [SMALL_STATE(10)] = 226,
  [SMALL_STATE(11)] = 245,
  [SMALL_STATE(12)] = 257,
  [SMALL_STATE(13)] = 269,
  [SMALL_STATE(14)] = 282,
  [SMALL_STATE(15)] = 293,
  [SMALL_STATE(16)] = 304,
  [SMALL_STATE(17)] = 315,
  [SMALL_STATE(18)] = 325,
  [SMALL_STATE(19)] = 334,
  [SMALL_STATE(20)] = 347,
  [SMALL_STATE(21)] = 360,
  [SMALL_STATE(22)] = 373,
  [SMALL_STATE(23)] = 386,
  [SMALL_STATE(24)] = 399,
  [SMALL_STATE(25)] = 412,
  [SMALL_STATE(26)] = 425,
  [SMALL_STATE(27)] = 438,
  [SMALL_STATE(28)] = 451,
  [SMALL_STATE(29)] = 460,
  [SMALL_STATE(30)] = 473,
  [SMALL_STATE(31)] = 486,
  [SMALL_STATE(32)] = 499,
  [SMALL_STATE(33)] = 512,
  [SMALL_STATE(34)] = 525,
  [SMALL_STATE(35)] = 538,
  [SMALL_STATE(36)] = 551,
  [SMALL_STATE(37)] = 560,
  [SMALL_STATE(38)] = 569,
  [SMALL_STATE(39)] = 582,
  [SMALL_STATE(40)] = 595,
  [SMALL_STATE(41)] = 608,
  [SMALL_STATE(42)] = 616,
  [SMALL_STATE(43)] = 626,
  [SMALL_STATE(44)] = 634,
  [SMALL_STATE(45)] = 642,
  [SMALL_STATE(46)] = 652,
  [SMALL_STATE(47)] = 660,
  [SMALL_STATE(48)] = 668,
  [SMALL_STATE(49)] = 678,
  [SMALL_STATE(50)] = 686,
  [SMALL_STATE(51)] = 696,
  [SMALL_STATE(52)] = 706,
  [SMALL_STATE(53)] = 714,
  [SMALL_STATE(54)] = 721,
  [SMALL_STATE(55)] = 728,
  [SMALL_STATE(56)] = 735,
  [SMALL_STATE(57)] = 742,
  [SMALL_STATE(58)] = 749,
  [SMALL_STATE(59)] = 756,
  [SMALL_STATE(60)] = 763,
  [SMALL_STATE(61)] = 770,
  [SMALL_STATE(62)] = 777,
  [SMALL_STATE(63)] = 784,
  [SMALL_STATE(64)] = 791,
  [SMALL_STATE(65)] = 798,
  [SMALL_STATE(66)] = 805,
  [SMALL_STATE(67)] = 812,
  [SMALL_STATE(68)] = 819,
  [SMALL_STATE(69)] = 826,
  [SMALL_STATE(70)] = 833,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer_type, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_schema_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_schema_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_schema_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin_type, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_type, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_type, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 5, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_type, 5, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_type, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 5, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meta_data_list, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_meta_data_list_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_meta_data_list_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_variant_list, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field_list, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_variant_list, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 5, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field_list, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_variant_list, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_variant_list_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_variant_list_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meta_data_list, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field_list, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_field_list_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_field_list_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 7, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meta_decl, 4, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meta_data_list, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_variant, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meta_data_entry, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [168] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_geno(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
